# Generated by Django 5.1.5 on 2025-02-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(db_default=0),
        ),
    ]
