# Generated by Django 5.1.5 on 2025-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_updated_at_notes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='likes',
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
