# Generated by Django 5.1.5 on 2025-02-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
